openapi: 3.0.3
info:
  title: 'API Documentation'
  description: 'This is the API documentation for our application.'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths: []
tags: []
